import type { KundaliData } from "@/components/kundali/KundaliForm";

/**
 * Generate an ultra-premium PDF Kundali report using jsPDF.
 * Runs entirely client-side with vector chart rendering.
 */
export async function generateKundaliPDF(data: KundaliData) {
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 12; // margin
  const CW = W - 2 * M; // content width
  let y = M;

  // Royal Celestial Color Palette
  type RGB = [number, number, number];
  const GOLD: RGB = [255, 185, 70];        // Premium Gold #ffb946
  const GOLD_DARK: RGB = [200, 135, 30];
  const BG_DARK: RGB = [12, 13, 24];         // Deep Obsidian #0c0d18
  const CARD_BG: RGB = [20, 22, 38];
  const CARD_BORDER: RGB = [45, 48, 75];
  const WHITE: RGB = [255, 255, 255];
  const MUTED: RGB = [160, 165, 190];
  const GREEN: RGB = [80, 200, 120];
  const RED: RGB = [230, 85, 85];

  // ── Helper Functions ──────────────────────

  function drawPageBg() {
    doc.setFillColor(...BG_DARK);
    doc.rect(0, 0, W, H, "F");
    // Outer Gold Page Border
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.4);
    doc.rect(5, 5, W - 10, H - 10, "S");
  }

  function checkPage(needed: number = 20) {
    if (y + needed > H - 14) {
      addFooter();
      doc.addPage();
      drawPageBg();
      y = M + 4;
    }
  }

  function addFooter() {
    const totalPages = doc.getNumberOfPages();
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by VivaAI Astrology (vivaai.in) • Official Lahiri Ayanamsa", W / 2, H - 7, { align: "center" });
    doc.text(`Page ${doc.getNumberOfPages()}`, W - M - 2, H - 7, { align: "right" });
  }

  function heading(text: string, fontSize = 12) {
    checkPage(18);
    doc.setFontSize(fontSize);
    doc.setTextColor(...GOLD);
    doc.setFont("helvetica", "bold");
    doc.text(text.toUpperCase(), M, y);
    y += 2;
    // Underline accent
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.5);
    doc.line(M, y, M + CW, y);
    y += 5;
  }

  function cardRow(items: { label: string; value: string; sub?: string }[], colWidth?: number) {
    const cols = items.length;
    const cw = colWidth || CW / cols;
    checkPage(16);

    items.forEach((item, i) => {
      const x = M + i * cw;
      doc.setFillColor(...CARD_BG);
      doc.setDrawColor(...CARD_BORDER);
      doc.roundedRect(x, y - 2, cw - 2, 14, 2, 2, "FD");

      doc.setFontSize(6);
      doc.setTextColor(...MUTED);
      doc.setFont("helvetica", "normal");
      doc.text(item.label.toUpperCase(), x + (cw - 2) / 2, y + 2, { align: "center" });

      doc.setFontSize(8);
      doc.setTextColor(...WHITE);
      doc.setFont("helvetica", "bold");
      doc.text(item.value, x + (cw - 2) / 2, y + 6.5, { align: "center" });

      if (item.sub) {
        doc.setFontSize(6);
        doc.setTextColor(...GOLD);
        doc.setFont("helvetica", "normal");
        doc.text(item.sub, x + (cw - 2) / 2, y + 10.5, { align: "center" });
      }
    });
    y += 15;
  }

  function tableRow(cells: string[], isHeader = false, colWidths?: number[]) {
    checkPage(6);
    const defaultCols = Array(cells.length).fill(CW / cells.length);
    const cw = colWidths || defaultCols;

    if (isHeader) {
      doc.setFillColor(28, 30, 52);
      doc.rect(M, y - 3, CW, 5, "F");
      doc.setFontSize(7);
      doc.setTextColor(...GOLD);
      doc.setFont("helvetica", "bold");
    } else {
      doc.setFontSize(7);
      doc.setTextColor(...WHITE);
      doc.setFont("helvetica", "normal");
      doc.setDrawColor(35, 38, 60);
      doc.setLineWidth(0.15);
      doc.line(M, y + 1.5, M + CW, y + 1.5);
    }

    let x = M;
    cells.forEach((cell, i) => {
      doc.text(cell, x + 1, y, { maxWidth: cw[i] - 2 });
      x += cw[i];
    });
    y += 5;
  }

  // ── Vector North Indian Chart Drawing Function ────────────

  function drawNorthIndianVectorChart(cx: number, cy: number, size: number) {
    const half = size / 2;

    // Outer Square
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.6);
    doc.rect(cx, cy, size, size, "S");

    // Diagonals
    doc.setLineWidth(0.3);
    doc.line(cx, cy, cx + size, cy + size);
    doc.line(cx + size, cy, cx, cy + size);

    // Inner Diamond
    doc.line(cx + half, cy, cx + size, cy + half);
    doc.line(cx + size, cy + half, cx + half, cy + size);
    doc.line(cx + half, cy + size, cx, cy + half);
    doc.line(cx, cy + half, cx + half, cy);

    // Map houses to positions inside vector box
    const lagnaIdx = data.lagna.degree !== undefined ? (data.planets.find(p => p.body === "Sun")?.signIndex ?? 0) : 0;
    const houseMap: Record<number, { planets: string[] }> = {};
    data.houses.forEach(h => { houseMap[h.house] = h; });

    const coords: Record<number, { sx: number; sy: number; px: number; py: number }> = {
      1:  { sx: cx + half, sy: cy + half * 0.6, px: cx + half, py: cy + half * 0.4 },
      2:  { sx: cx + half * 0.4, sy: cy + half * 0.25, px: cx + half * 0.3, py: cy + half * 0.4 },
      3:  { sx: cx + half * 0.2, sy: cy + half * 0.5, px: cx + half * 0.35, py: cy + half * 0.75 },
      4:  { sx: cx + half * 0.6, sy: cy + half, px: cx + half * 0.4, py: cy + half },
      5:  { sx: cx + half * 0.2, sy: cy + half * 1.5, px: cx + half * 0.35, py: cy + half * 1.25 },
      6:  { sx: cx + half * 0.4, sy: cy + half * 1.75, px: cx + half * 0.3, py: cy + half * 1.6 },
      7:  { sx: cx + half, sy: cy + half * 1.4, px: cx + half, py: cy + half * 1.6 },
      8:  { sx: cx + half * 1.6, sy: cy + half * 1.75, px: cx + half * 1.7, py: cy + half * 1.6 },
      9:  { sx: cx + half * 1.8, sy: cy + half * 1.5, px: cx + half * 1.65, py: cy + half * 1.25 },
      10: { sx: cx + half * 1.4, sy: cy + half, px: cx + half * 1.6, py: cy + half },
      11: { sx: cx + half * 1.8, sy: cy + half * 0.5, px: cx + half * 1.65, py: cy + half * 0.75 },
      12: { sx: cx + half * 1.6, sy: cy + half * 0.25, px: cx + half * 1.7, py: cy + half * 0.4 },
    };

    // Label House 1 LAGNA
    doc.setFontSize(6);
    doc.setTextColor(...GOLD);
    doc.setFont("helvetica", "bold");
    doc.text("LAGNA", cx + half, cy + 6, { align: "center" });

    // Draw house numbers and planet abbreviations
    for (let h = 1; h <= 12; h++) {
      const pos = coords[h];
      const signNum = ((data.lagna.lord ? (data.houses.find(x => x.house === 1)?.sign ? (["Mesha","Vrishabha","Mithuna","Karka","Simha","Kanya","Tula","Vrischika","Dhanu","Makara","Kumbha","Meena"].indexOf(data.houses.find(x => x.house === 1)!.sign)) : 0) : 0) + h - 1) % 12 + 1;

      doc.setFontSize(6);
      doc.setTextColor(...GOLD);
      doc.setFont("helvetica", "bold");
      doc.text(String(signNum), pos.sx, pos.sy, { align: "center" });

      const planets = houseMap[h]?.planets || [];
      if (planets.length > 0) {
        doc.setFontSize(5.5);
        doc.setTextColor(...GREEN);
        doc.setFont("helvetica", "bold");
        const pStr = planets.map(p => p.substring(0, 2)).join(",");
        doc.text(pStr, pos.px, pos.py, { align: "center" });
      }
    }
  }

  // ════════════════ PAGE 1 ════════════════

  drawPageBg();

  // Decorative Title Banner
  doc.setFillColor(22, 24, 45);
  doc.roundedRect(M, y, CW, 24, 3, 3, "F");
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.8);
  doc.roundedRect(M, y, CW, 24, 3, 3, "S");

  doc.setFontSize(16);
  doc.setTextColor(...GOLD);
  doc.setFont("helvetica", "bold");
  doc.text("VivaAI Astrology", W / 2, y + 8, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(...WHITE);
  doc.text("PREMIUM JANAM KUNDALI REPORT", W / 2, y + 14, { align: "center" });

  doc.setFontSize(6.5);
  doc.setTextColor(...MUTED);
  doc.text("High Precision Astronomical Formulas • Official Lahiri Ayanamsa", W / 2, y + 20, { align: "center" });

  y += 30;

  // Personal Info & Visual Chart side-by-side
  const chartSize = 65;
  const infoWidth = CW - chartSize - 6;

  // Draw Vector Birth Chart on top right
  drawNorthIndianVectorChart(M + infoWidth + 6, y, chartSize);

  // Left column: Personal Details
  doc.setFontSize(10);
  doc.setTextColor(...GOLD);
  doc.setFont("helvetica", "bold");
  doc.text("BIRTH DETAILS", M, y + 4);
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.4);
  doc.line(M, y + 6, M + infoWidth, y + 6);

  const detailsY = y + 10;
  doc.setFontSize(7.5);

  const fields = [
    { l: "Full Name", v: data.name },
    { l: "Gender", v: data.gender.toUpperCase() },
    { l: "Date of Birth", v: data.dob },
    { l: "Time of Birth", v: data.time },
    { l: "Place of Birth", v: data.place },
    { l: "Coordinates", v: `${data.latitude.toFixed(2)}°N, ${data.longitude.toFixed(2)}°E` },
    { l: "Timezone", v: data.timezone },
    { l: "Lahiri Ayanamsa", v: `${data.ayanamsa.toFixed(4)}°` },
  ];

  fields.forEach((f, idx) => {
    const fy = detailsY + idx * 6.5;
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text(`${f.l}:`, M, fy);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(String(f.v), M + 32, fy, { maxWidth: infoWidth - 34 });
  });

  y += chartSize + 8;

  // Core Planetary Archetypes
  heading("Core Celestial Archetypes", 11);
  cardRow([
    { label: "Lagna (Ascendant)", value: data.lagna.name, sub: `${data.lagna.lord} • ${data.lagna.degree.toFixed(1)}°` },
    { label: "Moon Sign (Rashi)", value: data.moonSign.name, sub: `Lord: ${data.moonSign.lord}` },
    { label: "Sun Sign", value: data.sunSign.name, sub: `Lord: ${data.sunSign.lord}` },
  ]);

  cardRow([
    { label: "Nakshatra", value: `${data.nakshatra.name} P${data.nakshatra.pada}`, sub: `Lord: ${data.nakshatra.lord}` },
    { label: "Deity", value: data.nakshatra.deity, sub: "Nakshatra Deity" },
    { label: "Gana / Nadi / Yoni", value: `${data.nakshatra.gana} • ${data.nakshatra.nadi}`, sub: `Yoni: ${data.nakshatra.yoni}` },
  ]);

  // Vimshottari Dasha
  heading("Vimshottari Dasha Timeline", 11);
  cardRow([
    { label: "Current Mahadasha", value: data.dasha.current, sub: data.dasha.currentRange },
    { label: "Antardasha (Sub-period)", value: data.dasha.antardasha, sub: "Active Sub-lord" },
  ], CW / 2);

  cardRow([
    { label: "Time Remaining", value: data.dasha.remaining, sub: `In ${data.dasha.current} Dasha` },
    { label: "Next Mahadasha", value: data.dasha.next, sub: `Starts at ${data.dasha.nextStartsAt} yrs` },
  ], CW / 2);

  // ════════════════ PAGE 2: Planetary & House Tables ════════════════

  checkPage(100);
  heading("Sidereal Planetary Positions (Lahiri)", 11);

  const planetCols = [24, 22, 18, 30, 30, 18, 38];
  tableRow(["Planet", "Lon°", "Sign°", "Rashi", "Nakshatra", "House", "Dignity"], true, planetCols);

  data.planets.forEach((p) => {
    tableRow([
      `${p.body}${p.isRetrograde ? " (R)" : ""}`,
      p.lon.toFixed(2) + "°",
      p.signDegree.toFixed(1) + "°",
      p.rashi,
      `${p.nakshatra} P${p.nakshatraPada}`,
      String(p.house),
      p.dignity || "Normal",
    ], false, planetCols);
  });
  y += 4;

  heading("Bhava (12 Houses) Analysis", 11);
  const houseCols = [18, 30, 30, 28, 74];
  tableRow(["House", "Sign", "English", "Lord", "Planets Present"], true, houseCols);

  data.houses.forEach((h) => {
    tableRow([
      `House ${h.house}`,
      h.sign,
      h.signEnglish,
      h.lord,
      h.planets.join(", ") || "—",
    ], false, houseCols);
  });
  y += 4;

  // Navamsa Table
  heading("Navamsa (D9 Chart) Placements", 11);
  const navCols = [30, 35, 35, 30, 50];
  tableRow(["Planet", "Navamsa Sign", "English", "Lord", "Navamsa Dignity"], true, navCols);

  (data.navamsa || []).forEach((n) => {
    tableRow([
      n.planet,
      n.navamsaSign,
      n.navamsaEnglish,
      n.navamsaLord,
      n.dignity,
    ], false, navCols);
  });
  y += 4;

  // ════════════════ PAGE 3: Doshas, Yogas & Life Predictions ════════════════

  checkPage(100);
  heading("Dosha Analysis", 11);

  const doshaList = [
    { name: "Manglik Dosha", active: data.doshas.manglik.status && !data.doshas.manglik.isCancelled, severity: data.doshas.manglik.severity, detail: data.doshas.manglik.details },
    { name: "Kaal Sarp Dosha", active: data.doshas.kaalSarp.status, severity: data.doshas.kaalSarp.status ? "Active" : "None", detail: data.doshas.kaalSarp.details },
    { name: "Sade Sati Phase", active: data.doshas.sadeSati.status, severity: data.doshas.sadeSati.phase, detail: data.doshas.sadeSati.details },
  ];

  doshaList.forEach((d) => {
    checkPage(16);
    const color = d.active ? RED : GREEN;
    doc.setFillColor(...CARD_BG);
    doc.roundedRect(M, y - 2, CW, 13, 2, 2, "F");
    doc.setFillColor(...color);
    doc.rect(M, y - 2, 2, 13, "F");

    doc.setFontSize(8.5);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(d.name, M + 5, y + 3);

    doc.setFontSize(7);
    doc.setTextColor(...color);
    doc.text(d.active ? d.severity : "Not Present", M + CW - 5, y + 3, { align: "right" });

    doc.setFontSize(6.5);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    const detailLines = doc.splitTextToSize(d.detail, CW - 12);
    doc.text(detailLines[0] || "", M + 5, y + 8);

    y += 15;
  });

  // Yogas
  heading("Formed Yogas Analysis", 11);
  const activeYogas = data.yogas.filter(y => y.formed);
  if (activeYogas.length === 0) {
    checkPage(8);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("No major yogas formed. Progress comes through consistent work.", M, y);
    y += 6;
  } else {
    activeYogas.forEach((yoga) => {
      checkPage(14);
      doc.setFillColor(...CARD_BG);
      doc.roundedRect(M, y - 2, CW, 12, 2, 2, "F");
      doc.setFillColor(...GREEN);
      doc.rect(M, y - 2, 2, 12, "F");

      doc.setFontSize(8.5);
      doc.setTextColor(...WHITE);
      doc.setFont("helvetica", "bold");
      doc.text(yoga.name, M + 5, y + 3);

      doc.setFontSize(6.5);
      doc.setTextColor(...GREEN);
      doc.text(`Active (${yoga.planets})`, M + CW - 5, y + 3, { align: "right" });

      doc.setFontSize(6.5);
      doc.setTextColor(...MUTED);
      doc.setFont("helvetica", "normal");
      const effLines = doc.splitTextToSize(yoga.effect, CW - 12);
      doc.text(effLines[0] || "", M + 5, y + 8);

      y += 14;
    });
  }

  // Predictions
  heading("Comprehensive Life Predictions", 11);

  const preds = [
    { title: "Personality & Temperament", text: data.personality },
    { title: "Career & Profession", text: data.career },
    { title: "Finance & Wealth", text: data.finance },
    { title: "Marriage & Relationships", text: data.marriage },
    { title: "Health & Wellness", text: data.health },
    { title: "Spiritual Path", text: data.spiritual },
  ];

  preds.forEach((p) => {
    checkPage(18);
    doc.setFontSize(8.5);
    doc.setTextColor(...GOLD);
    doc.setFont("helvetica", "bold");
    doc.text(`✦ ${p.title}`, M, y);
    y += 4;

    doc.setFontSize(7.5);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(p.text, CW);
    lines.forEach((l: string) => {
      checkPage(4);
      doc.text(l, M, y);
      y += 3.8;
    });
    y += 3;
  });

  // Gemstones & Remedies
  heading("Gemstones & Personalized Remedies", 11);

  data.luckyGems.forEach((g) => {
    checkPage(7);
    doc.setFontSize(8);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(`Gemstone: ${g.name}`, M, y);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text(`Planet: ${g.planet} • ${g.finger}`, M + 45, y);
    y += 5;
  });
  y += 2;

  cardRow([
    { label: "Lucky Numbers", value: data.luckyNumbers.join(", ") },
    { label: "Lucky Colors", value: data.luckyColors.join(", ") },
    { label: "Lucky Day", value: data.luckyDay },
  ]);

  data.remedies.forEach((r) => {
    checkPage(6);
    doc.setFontSize(7.5);
    doc.setTextColor(...GOLD);
    doc.text("•", M, y);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(r, CW - 6);
    lines.forEach((l: string) => {
      doc.text(l, M + 4, y);
      y += 3.8;
    });
  });

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter();
  }

  doc.save(`${data.name.replace(/\s+/g, "_")}_Kundali_VivaAI.pdf`);
}
