import type { KundaliData } from "@/components/kundali/KundaliForm";

/**
 * Generate a professional PDF Kundali report using jsPDF (loaded dynamically)
 * No server-side dependency — runs entirely in the browser.
 */
export async function generateKundaliPDF(data: KundaliData) {
  // Dynamic import — only loads when user actually downloads
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 15; // margin
  const CW = W - 2 * M; // content width
  let y = M;

  // Colors
  type RGB = [number, number, number];
  const GOLD: RGB = [255, 179, 71];       // #ffb347
  const DARK: RGB = [10, 11, 20];         // background
  const WHITE: RGB = [255, 255, 255];
  const MUTED: RGB = [160, 160, 180];
  const GREEN: RGB = [80, 200, 120];
  const RED: RGB = [220, 80, 80];

  // ── Helper Functions ──────────────────────

  function checkPage(needed: number = 20) {
    if (y + needed > H - 15) {
      addFooter();
      doc.addPage();
      y = M;
      drawPageBg();
    }
  }

  function drawPageBg() {
    doc.setFillColor(...DARK);
    doc.rect(0, 0, W, H, "F");
  }

  function addFooter() {
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text("Generated by VivaAI Astrology (vivaai.in) • Astronomy Engine + Lahiri Ayanamsa", W / 2, H - 8, { align: "center" });
    doc.text(`Page ${doc.getNumberOfPages()}`, W - M, H - 8, { align: "right" });
  }

  function heading(text: string, fontSize = 14) {
    checkPage(25);
    doc.setFontSize(fontSize);
    doc.setTextColor(...GOLD);
    doc.setFont("helvetica", "bold");
    doc.text(text, M, y);
    y += 2;
    // Gold underline
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.5);
    doc.line(M, y, M + CW, y);
    y += 6;
  }

  function subHeading(text: string) {
    checkPage(15);
    doc.setFontSize(10);
    doc.setTextColor(...GOLD);
    doc.setFont("helvetica", "bold");
    doc.text(text, M, y);
    y += 5;
  }

  function label(text: string, x: number) {
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text(text.toUpperCase(), x, y);
  }

  function value(text: string, x: number, color = WHITE) {
    doc.setFontSize(9);
    doc.setTextColor(...color);
    doc.setFont("helvetica", "bold");
    doc.text(text, x, y);
  }

  function bodyText(text: string, maxWidth = CW) {
    doc.setFontSize(8.5);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(text, maxWidth);
    for (const line of lines) {
      checkPage(5);
      doc.text(line, M, y);
      y += 4;
    }
    y += 2;
  }

  function cardRow(items: { label: string; value: string; sub?: string }[], colWidth?: number) {
    const cols = items.length;
    const cw = colWidth || CW / cols;
    checkPage(18);

    items.forEach((item, i) => {
      const x = M + i * cw;
      // Card background
      doc.setFillColor(20, 20, 35);
      doc.setDrawColor(50, 50, 70);
      doc.roundedRect(x, y - 3, cw - 2, 16, 2, 2, "FD");
      // Label
      doc.setFontSize(6);
      doc.setTextColor(...MUTED);
      doc.setFont("helvetica", "normal");
      doc.text(item.label.toUpperCase(), x + cw / 2 - 1, y + 1, { align: "center" });
      // Value
      doc.setFontSize(8);
      doc.setTextColor(...WHITE);
      doc.setFont("helvetica", "bold");
      doc.text(item.value, x + cw / 2 - 1, y + 6, { align: "center" });
      // Sub
      if (item.sub) {
        doc.setFontSize(6);
        doc.setTextColor(...MUTED);
        doc.setFont("helvetica", "normal");
        doc.text(item.sub, x + cw / 2 - 1, y + 10, { align: "center" });
      }
    });
    y += 18;
  }

  function tableRow(cells: string[], isHeader = false, colWidths?: number[]) {
    checkPage(7);
    const defaultCols = Array(cells.length).fill(CW / cells.length);
    const cw = colWidths || defaultCols;

    if (isHeader) {
      doc.setFillColor(25, 25, 40);
      doc.rect(M, y - 3.5, CW, 5.5, "F");
      doc.setFontSize(7);
      doc.setTextColor(...GOLD);
      doc.setFont("helvetica", "bold");
    } else {
      doc.setFontSize(7.5);
      doc.setTextColor(...WHITE);
      doc.setFont("helvetica", "normal");
      // Subtle row separator
      doc.setDrawColor(40, 40, 55);
      doc.setLineWidth(0.2);
      doc.line(M, y + 1.5, M + CW, y + 1.5);
    }

    let x = M;
    cells.forEach((cell, i) => {
      doc.text(cell, x + 1, y, { maxWidth: cw[i] - 2 });
      x += cw[i];
    });
    y += 5;
  }

  // ── Page 1: Cover / Header ──────────────

  drawPageBg();

  // Title bar
  doc.setFillColor(25, 22, 40);
  doc.roundedRect(M, y, CW, 30, 3, 3, "F");
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.8);
  doc.roundedRect(M, y, CW, 30, 3, 3, "S");

  doc.setFontSize(18);
  doc.setTextColor(...GOLD);
  doc.setFont("helvetica", "bold");
  doc.text("VivaAI Astrology", W / 2, y + 10, { align: "center" });

  doc.setFontSize(12);
  doc.setTextColor(...WHITE);
  doc.text("Vedic Kundali Report", W / 2, y + 18, { align: "center" });

  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text("Powered by Astronomy Engine + Lahiri Ayanamsa", W / 2, y + 25, { align: "center" });

  y += 38;

  // Personal info
  heading("Personal Details", 12);

  const col1W = CW / 3;
  cardRow([
    { label: "Full Name", value: data.name },
    { label: "Gender", value: data.gender },
    { label: "Date of Birth", value: data.dob },
  ]);
  cardRow([
    { label: "Time of Birth", value: data.time },
    { label: "Place", value: data.place.length > 25 ? data.place.substring(0, 22) + "..." : data.place },
    { label: "Timezone", value: data.timezone },
  ]);
  cardRow([
    { label: "Latitude", value: `${data.latitude.toFixed(4)}° N` },
    { label: "Longitude", value: `${data.longitude.toFixed(4)}° E` },
    { label: "Ayanamsa (Lahiri)", value: `${data.ayanamsa.toFixed(4)}°` },
  ]);

  // ── Birth Chart Summary ──────────────

  heading("Birth Chart Summary", 12);
  cardRow([
    { label: "Lagna (Ascendant)", value: `${data.lagna.name}`, sub: `Lord: ${data.lagna.lord} • ${data.lagna.degree.toFixed(1)}°` },
    { label: "Moon Sign (Rashi)", value: `${data.moonSign.name}`, sub: `Lord: ${data.moonSign.lord}` },
    { label: "Sun Sign", value: `${data.sunSign.name}`, sub: `Lord: ${data.sunSign.lord}` },
  ]);
  cardRow([
    { label: "Nakshatra", value: `${data.nakshatra.name} P${data.nakshatra.pada}`, sub: `Lord: ${data.nakshatra.lord}` },
    { label: "Deity", value: data.nakshatra.deity, sub: "Nakshatra Deity" },
    { label: "Gana", value: data.nakshatra.gana, sub: "Temperament" },
  ]);

  // ── Vimshottari Dasha ──────────────

  heading("Vimshottari Dasha", 12);
  cardRow([
    { label: "Mahadasha", value: data.dasha.current, sub: data.dasha.currentRange },
    { label: "Antardasha", value: data.dasha.antardasha, sub: "Sub-period" },
  ], CW / 2);
  cardRow([
    { label: "Remaining", value: data.dasha.remaining, sub: "In current period" },
    { label: "Next Mahadasha", value: data.dasha.next, sub: `Starts at ${data.dasha.nextStartsAt} yrs` },
  ], CW / 2);

  // ── Planetary Positions Table ──────────────

  heading("Planetary Positions (Sidereal — Lahiri)", 12);

  const planetCols = [24, 22, 18, 30, 30, 18, 38];
  tableRow(["Planet", "Lon°", "Sign°", "Rashi", "Nakshatra", "House", "Dignity"], true, planetCols);

  data.planets.forEach((p) => {
    tableRow([
      p.body,
      p.lon.toFixed(2) + "°",
      p.signDegree.toFixed(1) + "°",
      p.rashi,
      `${p.nakshatra} P${p.nakshatraPada}`,
      String(p.house),
      p.dignity,
    ], false, planetCols);
  });
  y += 3;

  // ── House Chart ──────────────

  heading("Bhava (House) Chart", 12);

  const houseCols = [18, 30, 30, 28, 74];
  tableRow(["House", "Sign", "English", "Lord", "Planets"], true, houseCols);

  data.houses.forEach((h) => {
    tableRow([
      String(h.house),
      h.sign,
      h.signEnglish,
      h.lord,
      h.planets.join(", ") || "—",
    ], false, houseCols);
  });
  y += 3;

  // ── Dosha Analysis ──────────────

  heading("Dosha Analysis", 12);

  const doshas = [
    { name: "Manglik Dosha", active: data.doshas.manglik.status, detail: data.doshas.manglik.details, severity: data.doshas.manglik.severity },
    { name: "Kaal Sarp Dosha", active: data.doshas.kaalSarp.status, detail: data.doshas.kaalSarp.details, severity: data.doshas.kaalSarp.status ? "Active" : "None" },
    { name: "Sade Sati", active: data.doshas.sadeSati.status, detail: data.doshas.sadeSati.details, severity: data.doshas.sadeSati.phase },
  ];

  doshas.forEach((d) => {
    checkPage(16);
    const statusColor = d.active ? RED : GREEN;
    doc.setFillColor(20, 20, 35);
    doc.roundedRect(M, y - 2, CW, 14, 2, 2, "F");
    // Left border
    doc.setFillColor(...statusColor);
    doc.rect(M, y - 2, 2, 14, "F");

    doc.setFontSize(9);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(d.name, M + 5, y + 3);

    doc.setFontSize(7);
    doc.setTextColor(...statusColor);
    doc.text(d.active ? d.severity : "Not Present", M + CW - 5, y + 3, { align: "right" });

    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    const detailLines = doc.splitTextToSize(d.detail, CW - 12);
    doc.text(detailLines[0] || "", M + 5, y + 9);

    y += 18;
  });

  // ── Yoga Analysis ──────────────

  heading("Yoga Analysis", 12);

  data.yogas.forEach((yoga) => {
    checkPage(14);
    doc.setFillColor(20, 20, 35);
    doc.roundedRect(M, y - 2, CW, 12, 2, 2, "F");

    if (yoga.formed) {
      doc.setFillColor(...GREEN);
      doc.rect(M, y - 2, 2, 12, "F");
    }

    doc.setFontSize(9);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(yoga.name, M + 5, y + 3);

    if (yoga.formed) {
      doc.setFontSize(6);
      doc.setTextColor(...GREEN);
      doc.text("ACTIVE", M + CW - 5, y + 3, { align: "right" });
    }

    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    const effectLines = doc.splitTextToSize(yoga.effect, CW - 12);
    doc.text(effectLines[0] || "", M + 5, y + 8);

    y += 16;
  });

  // ── Life Predictions ──────────────

  heading("Life Predictions", 12);

  const predictions = [
    { icon: "🧠", title: "Personality & Temperament", text: data.personality },
    { icon: "💼", title: "Career & Profession", text: data.career },
    { icon: "💰", title: "Finance & Wealth", text: data.finance },
    { icon: "💍", title: "Marriage & Relationships", text: data.marriage },
    { icon: "🏥", title: "Health & Wellness", text: data.health },
    { icon: "🕉", title: "Spiritual Path", text: data.spiritual },
  ];

  predictions.forEach((pred) => {
    subHeading(`${pred.title}`);
    bodyText(pred.text);
  });

  // ── Strengths ──────────────

  heading("Strengths", 12);
  data.positives.forEach((p) => {
    checkPage(6);
    doc.setFontSize(8);
    doc.setTextColor(...GREEN);
    doc.text("✦", M, y);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "normal");
    doc.text(p, M + 5, y);
    y += 5;
  });
  y += 3;

  // ── Challenges & Solutions ──────────────

  heading("Challenges & Solutions", 12);
  data.challenges.forEach((c) => {
    checkPage(14);
    doc.setFillColor(20, 20, 35);
    doc.roundedRect(M, y - 2, CW, 12, 2, 2, "F");
    doc.setFillColor(...GOLD);
    doc.rect(M, y - 2, 2, 12, "F");

    doc.setFontSize(7.5);
    doc.setTextColor(...GOLD);
    doc.setFont("helvetica", "bold");
    doc.text("Challenge:", M + 5, y + 3);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "normal");
    const issueLines = doc.splitTextToSize(c.issue, CW - 30);
    doc.text(issueLines[0], M + 25, y + 3);

    doc.setTextColor(...GREEN);
    doc.setFont("helvetica", "bold");
    doc.text("Solution:", M + 5, y + 8);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    const solLines = doc.splitTextToSize(c.solution, CW - 30);
    doc.text(solLines[0], M + 25, y + 8);

    y += 16;
  });

  // ── Gemstones & Lucky ──────────────

  heading("Gemstone & Lucky Recommendations", 12);

  data.luckyGems.forEach((g) => {
    checkPage(8);
    doc.setFontSize(8.5);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(`💎 ${g.name}`, M, y);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text(`For ${g.planet} • Wear on ${g.finger}`, M + 40, y);
    y += 6;
  });

  y += 3;
  cardRow([
    { label: "Lucky Numbers", value: data.luckyNumbers.join(", ") },
    { label: "Lucky Colors", value: data.luckyColors.join(", ") },
    { label: "Lucky Day", value: data.luckyDay },
  ]);

  // ── Remedies ──────────────

  heading("Personalized Remedies", 12);
  data.remedies.forEach((r) => {
    checkPage(6);
    doc.setFontSize(8);
    doc.setTextColor(...GOLD);
    doc.text("•", M, y);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(r, CW - 6);
    lines.forEach((line: string) => {
      doc.text(line, M + 4, y);
      y += 4;
    });
    y += 1;
  });

  // ── Final Footer ──────────────

  y += 5;
  checkPage(20);
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.5);
  doc.line(M, y, M + CW, y);
  y += 6;

  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(`Ayanamsa: ${data.ayanamsa.toFixed(4)}° (Lahiri) • Coordinates: ${data.latitude.toFixed(4)}°N, ${data.longitude.toFixed(4)}°E`, W / 2, y, { align: "center" });
  y += 5;
  doc.text("For major life decisions, please consult a qualified Vedic astrologer.", W / 2, y, { align: "center" });

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter();
  }

  // Save
  doc.save(`${data.name.replace(/\s+/g, "_")}_Kundali_VivaAI.pdf`);
}
