import type { KundaliData } from "@/components/kundali/KundaliForm";
import { northIndianCells, northIndianFrame } from "@/lib/astrology/chartGeometry";
import { sarvaVerdict } from "@/lib/astrology/ashtakavarga";

/**
 * Generate an ultra-premium PDF Kundali report using jsPDF.
 * Runs entirely client-side with vector chart rendering.
 */
export async function generateKundaliPDF(data: KundaliData) {
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 12; // margin
  const CW = W - 2 * M; // content width
  let y = M;

  // Royal Celestial Color Palette
  type RGB = [number, number, number];
  const GOLD: RGB = [255, 185, 70];        // Premium Gold #ffb946
  const GOLD_DARK: RGB = [200, 135, 30];
  const BG_DARK: RGB = [12, 13, 24];         // Deep Obsidian #0c0d18
  const CARD_BG: RGB = [20, 22, 38];
  const CARD_BORDER: RGB = [45, 48, 75];
  const WHITE: RGB = [255, 255, 255];
  const MUTED: RGB = [160, 165, 190];
  const GREEN: RGB = [80, 200, 120];
  const RED: RGB = [230, 85, 85];

  // ── Helper Functions ──────────────────────

  function drawPageBg() {
    doc.setFillColor(...BG_DARK);
    doc.rect(0, 0, W, H, "F");
    // Outer Gold Page Border
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.4);
    doc.rect(5, 5, W - 10, H - 10, "S");
  }

  function checkPage(needed: number = 20) {
    if (y + needed > H - 14) {
      addFooter();
      doc.addPage();
      drawPageBg();
      y = M + 4;
    }
  }

  function addFooter() {
    const totalPages = doc.getNumberOfPages();
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by VivaAI Astrology (vivaai.in) • Official Lahiri Ayanamsa", W / 2, H - 7, { align: "center" });
    doc.text(`Page ${doc.getNumberOfPages()}`, W - M - 2, H - 7, { align: "right" });
  }

  function heading(text: string, fontSize = 12) {
    checkPage(18);
    doc.setFontSize(fontSize);
    doc.setTextColor(...GOLD);
    doc.setFont("helvetica", "bold");
    doc.text(text.toUpperCase(), M, y);
    y += 2;
    // Underline accent
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.5);
    doc.line(M, y, M + CW, y);
    y += 5;
  }

  function cardRow(items: { label: string; value: string; sub?: string }[], colWidth?: number) {
    const cols = items.length;
    const cw = colWidth || CW / cols;
    checkPage(16);

    items.forEach((item, i) => {
      const x = M + i * cw;
      doc.setFillColor(...CARD_BG);
      doc.setDrawColor(...CARD_BORDER);
      doc.roundedRect(x, y - 2, cw - 2, 14, 2, 2, "FD");

      doc.setFontSize(6);
      doc.setTextColor(...MUTED);
      doc.setFont("helvetica", "normal");
      doc.text(item.label.toUpperCase(), x + (cw - 2) / 2, y + 2, { align: "center" });

      doc.setFontSize(8);
      doc.setTextColor(...WHITE);
      doc.setFont("helvetica", "bold");
      doc.text(item.value, x + (cw - 2) / 2, y + 6.5, { align: "center" });

      if (item.sub) {
        doc.setFontSize(6);
        doc.setTextColor(...GOLD);
        doc.setFont("helvetica", "normal");
        doc.text(item.sub, x + (cw - 2) / 2, y + 10.5, { align: "center" });
      }
    });
    y += 15;
  }

  function tableRow(cells: string[], isHeader = false, colWidths?: number[]) {
    checkPage(6);
    const defaultCols = Array(cells.length).fill(CW / cells.length);
    const cw = colWidths || defaultCols;

    if (isHeader) {
      doc.setFillColor(28, 30, 52);
      doc.rect(M, y - 3, CW, 5, "F");
      doc.setFontSize(7);
      doc.setTextColor(...GOLD);
      doc.setFont("helvetica", "bold");
    } else {
      doc.setFontSize(7);
      doc.setTextColor(...WHITE);
      doc.setFont("helvetica", "normal");
      doc.setDrawColor(35, 38, 60);
      doc.setLineWidth(0.15);
      doc.line(M, y + 1.5, M + CW, y + 1.5);
    }

    let x = M;
    cells.forEach((cell, i) => {
      doc.text(cell, x + 1, y, { maxWidth: cw[i] - 2 });
      x += cw[i];
    });
    y += 5;
  }

  // ── Vector North Indian Chart Drawing Function ────────────

  /**
   * Draws the North Indian chart from the same geometry the web chart uses.
   *
   * This used to carry its own hand-typed coordinate table, with the same
   * out-of-polygon label placements as the old web chart — and it derived the
   * Ascendant from the Sun's sign index, so the Rashi numbers printed around
   * the diamond were wrong for anyone not born at sunrise.
   */
  function drawNorthIndianVectorChart(cx: number, cy: number, size: number) {
    const cells = northIndianCells(size, 0);
    const frame = northIndianFrame(size, 0);
    const lagnaIdx = data.lagnaSignIndex;

    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.6);
    doc.rect(cx + frame.outer.x, cy + frame.outer.y, frame.outer.w, frame.outer.h, "S");

    doc.setLineWidth(0.3);
    for (const d of frame.diagonals) {
      doc.line(cx + d.x1, cy + d.y1, cx + d.x2, cy + d.y2);
    }
    const diamond = frame.diamond.split(" ").map((pair) => pair.split(",").map(Number));
    for (let i = 0; i < diamond.length; i++) {
      const a = diamond[i];
      const b = diamond[(i + 1) % diamond.length];
      doc.line(cx + a[0], cy + a[1], cx + b[0], cy + b[1]);
    }

    const byHouse = new Map(data.houses.map((h) => [h.house, h]));
    const degreeOf = new Map(data.planets.map((p) => [p.body, p]));

    for (const cell of cells) {
      const house = cell.index;

      doc.setFontSize(5.5);
      doc.setTextColor(...GOLD);
      doc.setFont("helvetica", "bold");
      doc.text(
        String(((lagnaIdx + house - 1) % 12) + 1),
        cx + cell.signAnchor.x,
        cy + cell.signAnchor.y,
        { align: "center" }
      );

      if (house === 1) {
        doc.setFontSize(4.5);
        doc.text("ASC", cx + cell.centroid.x, cy + cell.top + 4, { align: "center" });
      }

      const occupants = byHouse.get(house)?.planets ?? [];
      if (occupants.length === 0) continue;

      // One planet per line, centred on the centroid, so nothing overlaps.
      doc.setFontSize(occupants.length > 3 ? 4.2 : 5);
      doc.setFont("helvetica", "bold");
      const lineH = occupants.length > 3 ? 2.2 : 2.8;
      const startY = cy + cell.centroid.y - ((occupants.length - 1) * lineH) / 2;

      occupants.forEach((body, i) => {
        const p = degreeOf.get(body);
        doc.setTextColor(...(p?.isRetrograde ? RED : GREEN));
        const label = p
          ? `${body.substring(0, 2)}${p.isRetrograde ? "(R)" : ""} ${Math.floor(p.signDegree)}`
          : body.substring(0, 2);
        doc.text(label, cx + cell.centroid.x, startY + i * lineH, { align: "center" });
      });
    }
  }

  // ════════════════ PAGE 1 ════════════════

  drawPageBg();

  // Decorative Title Banner
  doc.setFillColor(22, 24, 45);
  doc.roundedRect(M, y, CW, 24, 3, 3, "F");
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.8);
  doc.roundedRect(M, y, CW, 24, 3, 3, "S");

  doc.setFontSize(16);
  doc.setTextColor(...GOLD);
  doc.setFont("helvetica", "bold");
  doc.text("VivaAI Astrology", W / 2, y + 8, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(...WHITE);
  doc.text("PREMIUM JANAM KUNDALI REPORT", W / 2, y + 14, { align: "center" });

  doc.setFontSize(6.5);
  doc.setTextColor(...MUTED);
  doc.text("High Precision Astronomical Formulas • Official Lahiri Ayanamsa", W / 2, y + 20, { align: "center" });

  y += 30;

  // Personal Info & Visual Chart side-by-side
  const chartSize = 65;
  const infoWidth = CW - chartSize - 6;

  // Draw Vector Birth Chart on top right
  drawNorthIndianVectorChart(M + infoWidth + 6, y, chartSize);

  // Left column: Personal Details
  doc.setFontSize(10);
  doc.setTextColor(...GOLD);
  doc.setFont("helvetica", "bold");
  doc.text("BIRTH DETAILS", M, y + 4);
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.4);
  doc.line(M, y + 6, M + infoWidth, y + 6);

  const detailsY = y + 10;
  doc.setFontSize(7.5);

  const fields = [
    { l: "Full Name", v: data.name },
    { l: "Gender", v: data.gender.toUpperCase() },
    { l: "Date of Birth", v: data.dob },
    { l: "Time of Birth", v: data.time },
    { l: "Place of Birth", v: data.place },
    { l: "Coordinates", v: `${data.latitude.toFixed(2)}°N, ${data.longitude.toFixed(2)}°E` },
    { l: "Timezone", v: data.timezone },
    { l: "Lahiri Ayanamsa", v: `${data.ayanamsa.toFixed(4)}°` },
  ];

  fields.forEach((f, idx) => {
    const fy = detailsY + idx * 6.5;
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text(`${f.l}:`, M, fy);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(String(f.v), M + 32, fy, { maxWidth: infoWidth - 34 });
  });

  y += chartSize + 8;

  // Core Planetary Archetypes
  heading("Core Celestial Archetypes", 11);
  cardRow([
    { label: "Lagna (Ascendant)", value: data.lagna.name, sub: `${data.lagna.lord} • ${data.lagna.degree.toFixed(1)}°` },
    { label: "Moon Sign (Rashi)", value: data.moonSign.name, sub: `Lord: ${data.moonSign.lord}` },
    { label: "Sun Sign", value: data.sunSign.name, sub: `Lord: ${data.sunSign.lord}` },
  ]);

  cardRow([
    { label: "Nakshatra", value: `${data.nakshatra.name} P${data.nakshatra.pada}`, sub: `Lord: ${data.nakshatra.lord}` },
    { label: "Deity", value: data.nakshatra.deity, sub: "Nakshatra Deity" },
    { label: "Gana / Nadi / Yoni", value: `${data.nakshatra.gana} • ${data.nakshatra.nadi}`, sub: `Yoni: ${data.nakshatra.yoni}` },
  ]);

  // Vimshottari Dasha
  heading("Vimshottari Dasha Timeline", 11);
  cardRow([
    { label: "Current Mahadasha", value: data.dasha.current, sub: data.dasha.currentRange },
    { label: "Antardasha (Sub-period)", value: data.dasha.antardasha, sub: "Active Sub-lord" },
  ], CW / 2);

  cardRow([
    { label: "Time Remaining", value: data.dasha.remaining, sub: `In ${data.dasha.current} Dasha` },
    { label: "Next Mahadasha", value: data.dasha.next, sub: `Starts at ${data.dasha.nextStartsAt} yrs` },
  ], CW / 2);

  // ════════════════ PAGE 2: Planetary & House Tables ════════════════

  checkPage(100);
  heading("Sidereal Planetary Positions (Lahiri)", 11);

  const planetCols = [24, 22, 18, 30, 30, 18, 38];
  tableRow(["Planet", "Lon°", "Sign°", "Rashi", "Nakshatra", "House", "Dignity"], true, planetCols);

  data.planets.forEach((p) => {
    tableRow([
      `${p.body}${p.isRetrograde ? " (R)" : ""}`,
      p.lon.toFixed(2) + "°",
      p.signDegree.toFixed(1) + "°",
      p.rashi,
      `${p.nakshatra} P${p.nakshatraPada}`,
      String(p.house),
      p.dignity || "Normal",
    ], false, planetCols);
  });
  y += 4;

  heading("Bhava (12 Houses) Analysis", 11);
  const houseCols = [18, 30, 30, 28, 74];
  tableRow(["House", "Sign", "English", "Lord", "Planets Present"], true, houseCols);

  data.houses.forEach((h) => {
    tableRow([
      `House ${h.house}`,
      h.sign,
      h.signEnglish,
      h.lord,
      h.planets.join(", ") || "—",
    ], false, houseCols);
  });
  y += 4;

  // Navamsa Table
  heading("Navamsa (D9 Chart) Placements", 11);
  const navCols = [30, 35, 35, 30, 50];
  tableRow(["Planet", "Navamsa Sign", "English", "Lord", "Navamsa Dignity"], true, navCols);

  (data.navamsa || []).forEach((n) => {
    tableRow([
      n.planet,
      n.navamsaSign,
      n.navamsaEnglish,
      n.navamsaLord,
      n.dignity,
    ], false, navCols);
  });
  y += 4;

  // ════════════════ Shadbala ════════════════

  checkPage(70);
  heading("Shadbala — Six-Fold Planetary Strength", 11);

  doc.setFontSize(6.5);
  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.text(
    doc.splitTextToSize(
      "Parashara sets a required minimum for each planet. The ratio to that minimum matters more than the raw total: below 100%, a planet still signifies its matters but cannot bring them about on its own schedule. Figures in Rupas.",
      CW
    ),
    M,
    y
  );
  y += 9;

  const balaCols = [26, 26, 26, 26, 30, 46];
  tableRow(["Planet", "Total", "Required", "% of min", "Verdict", "Strongest component"], true, balaCols);

  [...data.shadbala].sort((a, b) => b.ratio - a.ratio).forEach((s) => {
    const parts: [string, number][] = [
      ["Positional", s.breakdown.sthanaTotal / 5],
      ["Directional", s.breakdown.dig],
      ["Temporal", s.breakdown.kalaTotal / 5],
      ["Motional", s.breakdown.cheshta],
      ["Natural", s.breakdown.naisargika],
    ];
    const strongest = parts.reduce((a, c) => (c[1] > a[1] ? c : a));
    tableRow([
      s.planet,
      s.totalRupas.toFixed(2),
      String(s.requiredRupas),
      `${Math.round(s.ratio * 100)}%`,
      s.verdict,
      strongest[0],
    ], false, balaCols);
  });
  y += 4;

  // ════════════════ Ashtakavarga ════════════════

  checkPage(80);
  heading("Ashtakavarga — Bindu Support by House", 11);

  doc.setFontSize(6.5);
  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.text(
    doc.splitTextToSize(
      `Each sign is scored by how much support it receives from the whole chart. The seven individual charts sum to ${data.ashtakavarga.sarvaTotal} bindus (classical check figure: 337). Average per sign is 28; transits through high-bindu signs tend to go well.`,
      CW
    ),
    M,
    y
  );
  y += 9;

  const avCols = [24, ...Array(12).fill((CW - 24 - 20) / 12), 20];
  tableRow(
    ["Planet", ...Array.from({ length: 12 }, (_, i) => String(i + 1)), "Tot"],
    true,
    avCols
  );

  data.ashtakavarga.bhinna.forEach((b) => {
    tableRow(
      [
        b.planet,
        ...Array.from({ length: 12 }, (_, i) =>
          String(b.bindusBySign[(data.lagnaSignIndex + i) % 12])
        ),
        String(b.total),
      ],
      false,
      avCols
    );
  });

  tableRow(
    [
      "Sarva",
      ...Array.from({ length: 12 }, (_, i) =>
        String(data.ashtakavarga.sarvaBySign[(data.lagnaSignIndex + i) % 12])
      ),
      String(data.ashtakavarga.sarvaTotal),
    ],
    false,
    avCols
  );
  y += 3;

  doc.setFontSize(6);
  doc.setTextColor(...MUTED);
  const best = data.ashtakavarga.strongestSigns[0];
  const worst = data.ashtakavarga.weakestSigns[0];
  const bestHouse = ((best - data.lagnaSignIndex + 12) % 12) + 1;
  const worstHouse = ((worst - data.lagnaSignIndex + 12) % 12) + 1;
  doc.text(
    doc.splitTextToSize(
      `Columns are houses from your Ascendant. Best supported: house ${bestHouse} with ${data.ashtakavarga.sarvaBySign[best]} bindus (${sarvaVerdict(data.ashtakavarga.sarvaBySign[best]).label.toLowerCase()}). Weakest: house ${worstHouse} with ${data.ashtakavarga.sarvaBySign[worst]} bindus.`,
      CW
    ),
    M,
    y
  );
  y += 8;

  // ════════════════ Planet-by-planet analysis ════════════════

  checkPage(60);
  heading("Planet-by-Planet Analysis", 11);

  data.planetReports.forEach((r) => {
    checkPage(40);

    doc.setFillColor(...CARD_BG);
    doc.roundedRect(M, y - 3, CW, 8, 2, 2, "F");
    doc.setFontSize(9);
    doc.setTextColor(...GOLD);
    doc.setFont("helvetica", "bold");
    doc.text(`${r.planet} — ${r.placement}`, M + 3, y + 2.5);
    doc.setFontSize(6.5);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text(r.rulership.nature, M + CW - 3, y + 2.5, { align: "right" });
    y += 10;

    const para = (text: string, color: RGB = MUTED, size = 6.8) => {
      const lines = doc.splitTextToSize(text, CW - 4);
      checkPage(lines.length * 3 + 3);
      doc.setFontSize(size);
      doc.setTextColor(...color);
      doc.setFont("helvetica", "normal");
      doc.text(lines, M + 2, y);
      y += lines.length * 3 + 1.5;
    };

    const bullets = (title: string, items: string[], color: RGB) => {
      if (items.length === 0) return;
      checkPage(8);
      doc.setFontSize(6.5);
      doc.setTextColor(...color);
      doc.setFont("helvetica", "bold");
      doc.text(title.toUpperCase(), M + 2, y);
      y += 3.5;
      items.forEach((t) => para(`•  ${t}`));
    };

    para(r.significations, WHITE, 7);
    bullets("Strengths", r.strengths, GREEN);
    bullets("Weaknesses", r.weaknesses, RED);
    bullets("How it acts", r.effects, GOLD);
    para(`Timing: ${r.timing}`);
    para(`Strengthening it: ${r.remedy}`, GOLD);
    y += 3;
  });

  // ════════════════ PAGE 3: Doshas, Yogas & Life Predictions ════════════════

  checkPage(100);
  heading("Dosha Analysis", 11);

  const doshaList = [
    { name: "Manglik Dosha", active: data.doshas.manglik.status && !data.doshas.manglik.isCancelled, severity: data.doshas.manglik.severity, detail: data.doshas.manglik.details },
    { name: "Kaal Sarp Dosha", active: data.doshas.kaalSarp.status, severity: data.doshas.kaalSarp.status ? "Active" : "None", detail: data.doshas.kaalSarp.details },
    { name: "Sade Sati Phase", active: data.doshas.sadeSati.status, severity: data.doshas.sadeSati.phase, detail: data.doshas.sadeSati.details },
  ];

  doshaList.forEach((d) => {
    checkPage(16);
    const color = d.active ? RED : GREEN;
    doc.setFillColor(...CARD_BG);
    doc.roundedRect(M, y - 2, CW, 13, 2, 2, "F");
    doc.setFillColor(...color);
    doc.rect(M, y - 2, 2, 13, "F");

    doc.setFontSize(8.5);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(d.name, M + 5, y + 3);

    doc.setFontSize(7);
    doc.setTextColor(...color);
    doc.text(d.active ? d.severity : "Not Present", M + CW - 5, y + 3, { align: "right" });

    doc.setFontSize(6.5);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    const detailLines = doc.splitTextToSize(d.detail, CW - 12);
    doc.text(detailLines[0] || "", M + 5, y + 8);

    y += 15;
  });

  // Yogas
  heading("Formed Yogas Analysis", 11);
  const activeYogas = data.yogas.filter(y => y.formed);
  if (activeYogas.length === 0) {
    checkPage(8);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("No major yogas formed. Progress comes through consistent work.", M, y);
    y += 6;
  } else {
    activeYogas.forEach((yoga) => {
      checkPage(14);
      doc.setFillColor(...CARD_BG);
      doc.roundedRect(M, y - 2, CW, 12, 2, 2, "F");
      doc.setFillColor(...GREEN);
      doc.rect(M, y - 2, 2, 12, "F");

      doc.setFontSize(8.5);
      doc.setTextColor(...WHITE);
      doc.setFont("helvetica", "bold");
      doc.text(yoga.name, M + 5, y + 3);

      doc.setFontSize(6.5);
      doc.setTextColor(...GREEN);
      doc.text(`Active (${yoga.planets})`, M + CW - 5, y + 3, { align: "right" });

      doc.setFontSize(6.5);
      doc.setTextColor(...MUTED);
      doc.setFont("helvetica", "normal");
      const effLines = doc.splitTextToSize(yoga.effect, CW - 12);
      doc.text(effLines[0] || "", M + 5, y + 8);

      y += 14;
    });
  }

  // Predictions
  heading("Comprehensive Life Predictions", 11);

  const preds = [
    { title: "Personality & Temperament", text: data.personality },
    { title: "Career & Profession", text: data.career },
    { title: "Finance & Wealth", text: data.finance },
    { title: "Marriage & Relationships", text: data.marriage },
    { title: "Health & Wellness", text: data.health },
    { title: "Spiritual Path", text: data.spiritual },
  ];

  preds.forEach((p) => {
    checkPage(18);
    doc.setFontSize(8.5);
    doc.setTextColor(...GOLD);
    doc.setFont("helvetica", "bold");
    doc.text(`✦ ${p.title}`, M, y);
    y += 4;

    doc.setFontSize(7.5);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(p.text, CW);
    lines.forEach((l: string) => {
      checkPage(4);
      doc.text(l, M, y);
      y += 3.8;
    });
    y += 3;
  });

  // Gemstones & Remedies
  heading("Gemstones & Personalized Remedies", 11);

  data.luckyGems.forEach((g) => {
    checkPage(7);
    doc.setFontSize(8);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "bold");
    doc.text(`Gemstone: ${g.name}`, M, y);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text(`Planet: ${g.planet} • ${g.finger}`, M + 45, y);
    y += 5;
  });
  y += 2;

  cardRow([
    { label: "Lucky Numbers", value: data.luckyNumbers.join(", ") },
    { label: "Lucky Colors", value: data.luckyColors.join(", ") },
    { label: "Lucky Day", value: data.luckyDay },
  ]);

  data.remedies.forEach((r) => {
    checkPage(6);
    doc.setFontSize(7.5);
    doc.setTextColor(...GOLD);
    doc.text("•", M, y);
    doc.setTextColor(...WHITE);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(r, CW - 6);
    lines.forEach((l: string) => {
      doc.text(l, M + 4, y);
      y += 3.8;
    });
  });

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter();
  }

  doc.save(`${data.name.replace(/\s+/g, "_")}_Kundali_VivaAI.pdf`);
}
